version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgresRK
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
