version: "3.5"

services:
  postgres:
    image: postgres
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
