services:
  api:
    container_name: apiRK
    build: .
    ports:
      - "3335:3335"
    depends_on:
      - db
    networks:
      - rk_network

  db:
    image: postgres
    container_name: dbRK
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - rk_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - rk_network

volumes:
  rk_data:

networks:
  rk_network:
    driver: bridge
