services:
  postgres:
    image: postgres
    container_name: dbRK
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5435:5432"

volumes:
  db:
